<?php

namespace Slub\Dfgviewer\Common;

/**
 * Copyright notice
 *
 * (c) Saxon State and University Library Dresden <typo3@slub-dresden.de>
 * All rights reserved
 *
 * This script is part of the TYPO3 project. The TYPO3 project is
 * free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * The GNU General Public License can be found at
 * http://www.gnu.org/copyleft/gpl.html.
 *
 * This script is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * This copyright notice MUST APPEAR in all copies of the script!
 */

/**
 * The language helper contains functions to handle ISO 639-2.
 *
 * @package TYPO3
 * @subpackage dfg-viewer
 *
 * @access public
 */
class IsoHelper
{
    /*
     *  Language array based on the ISO 639-2 code standard from the Library of Congress (https://www.loc.gov/standards/iso639-2/php/code_list.php).
     *
     *  Each element of the array uses an ISO 639-2 code as its key and contains an array with the language name in both English and German.
     *  Additionally, for 21 codes that have alternative versions for bibliographic or terminological purposes, a second array is included.
     *  This second array holds two values: the first is a boolean indicating whether it is a bibliographic code (true) or a terminological code (false),
     *  and the second is a reference to the alternative ISO code associated with that distinction.
     */
    public const array ISO_639_2 = [
        'aar' => [['Afar', 'Danakil-Sprache']],
        'abk' => [['Abkhazian', 'Abchasisch']],
        'ace' => [['Achinese', 'Aceh-Sprache']],
        'ach' => [['Acoli', 'Acholi-Sprache']],
        'ada' => [['Adangme', 'Adangme-Sprache']],
        'ady' => [['Adyghe; Adygei', 'Adygisch']],
        'afa' => [['Afro-Asiatic languages', 'Hamitosemitische Sprachen (Andere)']],
        'afh' => [['Afrihili', 'Afrihili']],
        'afr' => [['Afrikaans', 'Afrikaans']],
        'ain' => [['Ainu', 'Ainu-Sprache']],
        'aka' => [['Akan', 'Akan-Sprache']],
        'akk' => [['Akkadian', 'Akkadisch']],
        'alb' => [['Albanian', 'Albanisch'], [true, 'sqi']],
        'sqi' => [['Albanian', 'Albanisch'], [false, 'alb']],
        'ale' => [['Aleut', 'Aleutisch']],
        'alg' => [['Algonquian languages', 'Algonkin-Sprachen (Andere)']],
        'alt' => [['Southern Altai', 'Altaisch']],
        'amh' => [['Amharic', 'Amharisch']],
        'ang' => [['English, Old (ca.450-1100)', 'Altenglisch']],
        'anp' => [['Angika', 'Anga-Sprache']],
        'apa' => [['Apache languages', 'Apachen-Sprachen']],
        'ara' => [['Arabic', 'Arabisch']],
        'arc' => [['Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)', 'Aramäisch']],
        'arg' => [['Aragonese', 'Aragonesisch']],
        'arm' => [['Armenian', 'Armenisch'], [true, 'hye']],
        'hye' => [['Armenian', 'Armenisch'], [false, 'arm']],
        'arn' => [['Mapudungun; Mapuche', 'Arauka-Sprachen']],
        'arp' => [['Arapaho', 'Arapaho-Sprache']],
        'art' => [['Artificial languages', 'Kunstsprachen (Andere)']],
        'arw' => [['Arawak', 'Arawak-Sprachen']],
        'asm' => [['Assamese', 'Assamesisch']],
        'ast' => [['Asturian; Bable; Leonese; Asturleonese', 'Asturisch']],
        'ath' => [['Athapascan languages', 'Athapaskische Sprachen (Andere)']],
        'aus' => [['Australian languages', 'Australische Sprachen']],
        'ava' => [['Avaric', 'Awarisch']],
        'ave' => [['Avestan', 'Avestisch']],
        'awa' => [['Awadhi', 'Awadhi']],
        'aym' => [['Aymara', 'Aymará-Sprache']],
        'aze' => [['Azerbaijani', 'Aserbeidschanisch']],
        'bad' => [['Banda languages', 'Banda-Sprachen (Ubangi-Sprachen)']],
        'bai' => [['Bamileke languages', 'Bamileke-Sprachen']],
        'bak' => [['Bashkir', 'Baschkirisch']],
        'bal' => [['Baluchi', 'Belutschisch']],
        'bam' => [['Bambara', 'Bambara-Sprache']],
        'ban' => [['Balinese', 'Balinesisch']],
        'baq' => [['Basque', 'Baskisch'], [true, 'eus']],
        'eus' => [['Basque', 'Baskisch'], [false, 'baq']],
        'bas' => [['Basa', 'Basaa-Sprache']],
        'bat' => [['Baltic languages', 'Baltische Sprachen (Andere)']],
        'bej' => [['Beja; Bedawiyet', 'Bedauye']],
        'bel' => [['Belarusian', 'Weißrussisch']],
        'bem' => [['Bemba', 'Bemba-Sprache']],
        'ben' => [['Bengali', 'Bengali']],
        'ber' => [['Berber languages', 'Berbersprachen (Andere)']],
        'bho' => [['Bhojpuri', 'Bhojpuri']],
        'bih' => [['Bihari languages', 'Bihari (Andere)']],
        'bik' => [['Bikol', 'Bikol-Sprache']],
        'bin' => [['Bini; Edo', 'Edo-Sprache']],
        'bis' => [['Bislama', 'Beach-la-mar']],
        'bla' => [['Siksika', 'Blackfoot-Sprache']],
        'bnt' => [['Bantu languages', 'Bantusprachen (Andere)']],
        'tib' => [['Tibetan', 'Tibetisch'], [true, 'bod']],
        'bod' => [['Tibetan', 'Tibetisch'], [false, 'tib']],
        'bos' => [['Bosnian', 'Bosnisch']],
        'bra' => [['Braj', 'Braj-Bhakha']],
        'bre' => [['Breton', 'Bretonisch']],
        'btk' => [['Batak languages', 'Batak-Sprache']],
        'bua' => [['Buriat', 'Burjatisch']],
        'bug' => [['Buginese', 'Bugi-Sprache']],
        'bul' => [['Bulgarian', 'Bulgarisch']],
        'bur' => [['Burmese', 'Birmanisch'], [true, 'mya']],
        'mya' => [['Burmese', 'Birmanisch'], [false, 'bur']],
        'byn' => [['Blin; Bilin', 'Bilin-Sprache']],
        'cad' => [['Caddo', 'Caddo-Sprachen']],
        'cai' => [['Central American Indian languages', 'Indianersprachen, Zentralamerika (Andere)']],
        'car' => [['Galibi Carib', 'Karibische Sprachen']],
        'cat' => [['Catalan; Valencian', 'Katalanisch']],
        'cau' => [['Caucasian languages', 'Kaukasische Sprachen (Andere)']],
        'ceb' => [['Cebuano', 'Cebuano']],
        'cel' => [['Celtic languages', 'Keltische Sprachen (Andere)']],
        'cze' => [['Czech', 'Tschechisch'], [true, 'ces']],
        'ces' => [['Czech', 'Tschechisch'], [false, 'cze']],
        'cha' => [['Chamorro', 'Chamorro-Sprache']],
        'chb' => [['Chibcha', 'Chibcha-Sprachen']],
        'che' => [['Chechen', 'Tschetschenisch']],
        'chg' => [['Chagatai', 'Tschagataisch']],
        'chi' => [['Chinese', 'Chinesisch'], [true, 'zho']],
        'zho' => [['Chinese', 'Chinesisch'], [false, 'chi']],
        'chk' => [['Chuukese', 'Trukesisch']],
        'chm' => [['Mari', 'Tscheremissisch']],
        'chn' => [['Chinook jargon', 'Chinook-Jargon']],
        'cho' => [['Choctaw', 'Choctaw-Sprache']],
        'chp' => [['Chipewyan; Dene Suline', 'Chipewyan-Sprache']],
        'chr' => [['Cherokee', 'Cherokee-Sprache']],
        'chu' => [['Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic', 'Kirchenslawisch']],
        'chv' => [['Chuvash', 'Tschuwaschisch']],
        'chy' => [['Cheyenne', 'Cheyenne-Sprache']],
        'cmc' => [['Chamic languages', 'Cham-Sprachen']],
        'cnr' => [['Montenegrin', 'Montenegrinisch']],
        'cop' => [['Coptic', 'Koptisch']],
        'cor' => [['Cornish', 'Kornisch']],
        'cos' => [['Corsican', 'Korsisch']],
        'cpe' => [['Creoles and pidgins, English based', 'Kreolisch-Englisch (Andere)']],
        'cpf' => [['Creoles and pidgins, French-based', 'Kreolisch-Französisch (Andere)']],
        'cpp' => [['Creoles and pidgins, Portuguese-based', 'Kreolisch-Portugiesisch (Andere)']],
        'cre' => [['Cree', 'Cree-Sprache']],
        'crh' => [['Crimean Tatar; Crimean Turkish', 'Krimtatarisch']],
        'crp' => [['Creoles and pidgins', 'Kreolische Sprachen; Pidginsprachen (Andere)']],
        'csb' => [['Kashubian', 'Kaschubisch']],
        'cus' => [['Cushitic languages', 'Kuschitische Sprachen (Andere)']],
        'wel' => [['Welsh', 'Kymrisch'], [true, 'cym']],
        'cym' => [['Welsh', 'Kymrisch'], [false, 'wel']],
        'dak' => [['Dakota', 'Dakota-Sprache']],
        'dan' => [['Danish', 'Dänisch']],
        'dar' => [['Dargwa', 'Darginisch']],
        'day' => [['Land Dayak languages', 'Dajakisch']],
        'del' => [['Delaware', 'Delaware-Sprache']],
        'den' => [['Slave (Athapascan)', 'Slave-Sprache']],
        'ger' => [['German', 'Deutsch'], [true, 'deu']],
        'deu' => [['German', 'Deutsch'], [false, 'ger']],
        'dgr' => [['Tlicho; Dogrib', 'Tlicho-Sprache; Dogrib-Sprache']],
        'din' => [['Dinka', 'Dinka-Sprache']],
        'div' => [['Divehi; Dhivehi; Maldivian', 'Maledivisch']],
        'doi' => [['Dogri (macrolanguage)', 'Dogri']],
        'dra' => [['Dravidian languages', 'Drawidische Sprachen (Andere)']],
        'dsb' => [['Lower Sorbian', 'Niedersorbisch']],
        'dua' => [['Duala', 'Duala-Sprachen']],
        'dum' => [['Dutch, Middle (ca.1050-1350)', 'Mittelniederländisch']],
        'dut' => [['Dutch; Flemish', 'Niederländisch'], [true, 'nld']],
        'nld' => [['Dutch; Flemish', 'Niederländisch'], [false, 'dut']],
        'dyu' => [['Dyula', 'Dyula-Sprache']],
        'dzo' => [['Dzongkha', 'Dzongkha']],
        'efi' => [['Efik', 'Efik']],
        'egy' => [['Egyptian (Ancient)', 'Ägyptisch']],
        'eka' => [['Ekajuk', 'Ekajuk']],
        'gre' => [['Greek, Modern (1453-)', 'Neugriechisch'], [true, 'ell']],
        'ell' => [['Greek, Modern (1453-)', 'Neugriechisch'], [false, 'gre']],
        'elx' => [['Elamite', 'Elamisch']],
        'eng' => [['English', 'Englisch']],
        'enm' => [['English, Middle (1100-1500)', 'Mittelenglisch']],
        'epo' => [['Esperanto', 'Esperanto']],
        'est' => [['Estonian', 'Estnisch']],
        'ewe' => [['Ewe', 'Ewe-Sprache']],
        'ewo' => [['Ewondo', 'Ewondo']],
        'fan' => [['Fang', 'Pangwe-Sprache']],
        'fao' => [['Faroese', 'Färöisch']],
        'per' => [['Persian', 'Persisch'], [true, 'fas']],
        'fas' => [['Persian', 'Persisch'], [false, 'per']],
        'fat' => [['Fanti', 'Fante-Sprache']],
        'fij' => [['Fijian', 'Fidschi-Sprache']],
        'fil' => [['Filipino; Pilipino', 'Pilipino']],
        'fin' => [['Finnish', 'Finnisch']],
        'fiu' => [['Finno-Ugrian languages', 'Finnougrische Sprachen (Andere)']],
        'fon' => [['Fon', 'Fon-Sprache']],
        'fre' => [['French', 'Französisch'], [true, 'fra']],
        'fra' => [['French', 'Französisch'], [false, 'fre']],
        'frm' => [['French, Middle (ca.1400-1600)', 'Mittelfranzösisch']],
        'fro' => [['French, Old (842-ca.1400)', 'Altfranzösisch']],
        'frr' => [['Northern Frisian', 'Nordfriesisch']],
        'frs' => [['Eastern Frisian', 'Ostfriesisch']],
        'fry' => [['Western Frisian', 'Friesisch']],
        'ful' => [['Fulah', 'Ful']],
        'fur' => [['Friulian', 'Friulisch']],
        'gaa' => [['Ga', 'Ga-Sprache']],
        'gay' => [['Gayo', 'Gayo-Sprache']],
        'gba' => [['Gbaya', 'Gbaya-Sprache']],
        'gem' => [['Germanic languages', 'Germanische Sprachen (Andere)']],
        'geo' => [['Georgian', 'Georgisch'], [true, 'kat']],
        'kat' => [['Georgian', 'Georgisch'], [false, 'geo']],
        'gez' => [['Geez', 'Altäthiopisch']],
        'gil' => [['Gilbertese', 'Gilbertesisch']],
        'gla' => [['Gaelic; Scottish Gaelic', 'Gälisch-Schottisch']],
        'gle' => [['Irish', 'Irisch']],
        'glg' => [['Galician', 'Galicisch']],
        'glv' => [['Manx', 'Manx']],
        'gmh' => [['German, Middle High (ca.1050-1500)', 'Mittelhochdeutsch']],
        'goh' => [['German, Old High (ca.750-1050)', 'Althochdeutsch']],
        'gon' => [['Gondi', 'Gondi-Sprache']],
        'gor' => [['Gorontalo', 'Gorontalesisch']],
        'got' => [['Gothic', 'Gotisch']],
        'grb' => [['Grebo', 'Grebo-Sprache']],
        'grc' => [['Greek, Ancient (to 1453)', 'Griechisch']],
        'grn' => [['Guarani', 'Guaraní-Sprache']],
        'gsw' => [['Swiss German; Alemannic; Alsatian', 'Schweizerdeutsch']],
        'guj' => [['Gujarati', 'Gujarati-Sprache']],
        'gwi' => [['Gwich\'in', 'Kutchin-Sprache']],
        'hai' => [['Haida', 'Haida-Sprache']],
        'hat' => [['Haitian; Haitian Creole', 'Haïtien (Haiti-Kreolisch)']],
        'hau' => [['Hausa', 'Haussa-Sprache']],
        'haw' => [['Hawaiian', 'Hawaiisch']],
        'heb' => [['Hebrew', 'Hebräisch']],
        'her' => [['Herero', 'Herero-Sprache']],
        'hil' => [['Hiligaynon', 'Hiligaynon-Sprache']],
        'him' => [['Himachali languages; Western Pahari languages', 'Himachali']],
        'hin' => [['Hindi', 'Hindi']],
        'hit' => [['Hittite', 'Hethitisch']],
        'hmn' => [['Hmong; Mong', 'Miao-Sprachen']],
        'hmo' => [['Hiri Motu', 'Hiri-Motu']],
        'hrv' => [['Croatian', 'Kroatisch']],
        'hsb' => [['Upper Sorbian', 'Obersorbisch']],
        'hun' => [['Hungarian', 'Ungarisch']],
        'hup' => [['Hupa', 'Hupa-Sprache']],
        'iba' => [['Iban', 'Iban-Sprache']],
        'ibo' => [['Igbo', 'Ibo-Sprache']],
        'ice' => [['Icelandic', 'Isländisch'], [true, 'isl']],
        'isl' => [['Icelandic', 'Isländisch'], [false, 'ice']],
        'ido' => [['Ido', 'Ido']],
        'iii' => [['Sichuan Yi; Nuosu', 'Lalo-Sprache']],
        'ijo' => [['Ijo languages', 'Ijo-Sprache']],
        'iku' => [['Inuktitut', 'Inuktitut']],
        'ile' => [['Interlingue; Occidental', 'Interlingue']],
        'ilo' => [['Iloko', 'Ilokano-Sprache']],
        'ina' => [['Interlingua (International Auxiliary Language Association)', 'Interlingua']],
        'inc' => [['Indic languages', 'Indoarische Sprachen (Andere)']],
        'ind' => [['Indonesian', 'Bahasa Indonesia']],
        'ine' => [['Indo-European languages', 'Indogermanische Sprachen (Andere)']],
        'inh' => [['Ingush', 'Inguschisch']],
        'ipk' => [['Inupiaq', 'Inupik']],
        'ira' => [['Iranian languages', 'Iranische Sprachen (Andere)']],
        'iro' => [['Iroquoian languages', 'Irokesische Sprachen']],
        'ita' => [['Italian', 'Italienisch']],
        'jav' => [['Javanese', 'Javanisch']],
        'jbo' => [['Lojban', 'Lojban']],
        'jpn' => [['Japanese', 'Japanisch']],
        'jpr' => [['Judeo-Persian', 'Jüdisch-Persisch']],
        'jrb' => [['Judeo-Arabic', 'Jüdisch-Arabisch']],
        'kaa' => [['Kara-Kalpak', 'Karakalpakisch']],
        'kab' => [['Kabyle', 'Kabylisch']],
        'kac' => [['Kachin; Jingpho', 'Kachin-Sprache']],
        'kal' => [['Kalaallisut; Greenlandic', 'Grönländisch']],
        'kam' => [['Kamba', 'Kamba-Sprache']],
        'kan' => [['Kannada', 'Kannada']],
        'kar' => [['Karen languages', 'Karenisch']],
        'kas' => [['Kashmiri', 'Kaschmiri']],
        'kau' => [['Kanuri', 'Kanuri-Sprache']],
        'kaw' => [['Kawi', 'Kawi']],
        'kaz' => [['Kazakh', 'Kasachisch']],
        'kbd' => [['Kabardian', 'Kabardinisch']],
        'kha' => [['Khasi', 'Khasi-Sprache']],
        'khi' => [['Khoisan languages', 'Khoisan-Sprachen (Andere)']],
        'khm' => [['Central Khmer', 'Kambodschanisch']],
        'kho' => [['Khotanese; Sakan', 'Sakisch']],
        'kik' => [['Kikuyu; Gikuyu', 'Kikuyu-Sprache']],
        'kin' => [['Kinyarwanda', 'Rwanda-Sprache']],
        'kir' => [['Kirghiz; Kyrgyz', 'Kirgisisch']],
        'kmb' => [['Kimbundu', 'Kimbundu-Sprache']],
        'kok' => [['Konkani (macrolanguage)', 'Konkani']],
        'kom' => [['Komi', 'Komi-Sprache']],
        'kon' => [['Kongo', 'Kongo-Sprache']],
        'kor' => [['Korean', 'Koreanisch']],
        'kos' => [['Kosraean', 'Kosraeanisch']],
        'kpe' => [['Kpelle', 'Kpelle-Sprache']],
        'krc' => [['Karachay-Balkar', 'Karatschaiisch-Balkarisch']],
        'krl' => [['Karelian', 'Karelisch']],
        'kro' => [['Kru languages', 'Kru-Sprachen (Andere)']],
        'kru' => [['Kurukh', 'Oraon-Sprache']],
        'kua' => [['Kuanyama; Kwanyama', 'Kwanyama-Sprache']],
        'kum' => [['Kumyk', 'Kumükisch']],
        'kur' => [['Kurdish', 'Kurdisch']],
        'kut' => [['Kutenai', 'Kutenai-Sprache']],
        'lad' => [['Ladino', 'Judenspanisch']],
        'lah' => [['Lahnda', 'Lahnda']],
        'lam' => [['Lamba', 'Lamba-Sprache (Bantusprache)']],
        'lao' => [['Lao', 'Laotisch']],
        'lat' => [['Latin', 'Latein']],
        'lav' => [['Latvian', 'Lettisch']],
        'lez' => [['Lezghian', 'Lesgisch']],
        'lim' => [['Limburgan; Limburger; Limburgish', 'Limburgisch']],
        'lin' => [['Lingala', 'Lingala']],
        'lit' => [['Lithuanian', 'Litauisch']],
        'lol' => [['Mongo', 'Mongo-Sprache']],
        'loz' => [['Lozi', 'Rotse-Sprache']],
        'ltz' => [['Luxembourgish; Letzeburgesch', 'Luxemburgisch']],
        'lua' => [['Luba-Lulua', 'Lulua-Sprache']],
        'lub' => [['Luba-Katanga', 'Luba-Katanga-Sprache']],
        'lug' => [['Ganda', 'Ganda-Sprache']],
        'lui' => [['Luiseno', 'Luiseño-Sprache']],
        'lun' => [['Lunda', 'Lunda-Sprache']],
        'luo' => [['Luo (Kenya and Tanzania)', 'Luo-Sprache']],
        'lus' => [['Lushai', 'Lushai-Sprache']],
        'mac' => [['Macedonian', 'Makedonisch'], [true, 'mkd']],
        'mkd' => [['Macedonian', 'Makedonisch'], [false, 'mac']],
        'mad' => [['Madurese', 'Maduresisch']],
        'mag' => [['Magahi', 'Khotta']],
        'mah' => [['Marshallese', 'Marschallesisch']],
        'mai' => [['Maithili', 'Maithili']],
        'mak' => [['Makasar', 'Makassarisch']],
        'mal' => [['Malayalam', 'Malayalam']],
        'man' => [['Mandingo', 'Malinke-Sprache']],
        'mao' => [['Maori', 'Maori-Sprache'], [true, 'mri']],
        'mri' => [['Maori', 'Maori-Sprache'], [false, 'mao']],
        'map' => [['Austronesian languages', 'Austronesische Sprachen (Andere)']],
        'mar' => [['Marathi', 'Marathi']],
        'mas' => [['Masai', 'Massai-Sprache']],
        'may' => [['Malay (macrolanguage)', 'Malaiisch'], [true, 'msa']],
        'msa' => [['Malay (macrolanguage)', 'Malaiisch'], [false, 'may']],
        'mdf' => [['Moksha', 'Mokscha-Sprache']],
        'mdr' => [['Mandar', 'Mandaresisch']],
        'men' => [['Mende', 'Mende-Sprache']],
        'mga' => [['Irish, Middle (900-1200)', 'Mittelirisch']],
        'mic' => [['Mi\'kmaq; Micmac', 'Micmac-Sprache']],
        'min' => [['Minangkabau', 'Minangkabau-Sprache']],
        'mis' => [['Uncoded languages', 'Einzelne andere Sprachen']],
        'mkh' => [['Mon-Khmer languages', 'Mon-Khmer-Sprachen (Andere)']],
        'mlg' => [['Malagasy', 'Malagassi-Sprache']],
        'mlt' => [['Maltese', 'Maltesisch']],
        'mnc' => [['Manchu', 'Mandschurisch']],
        'mni' => [['Manipuri', 'Meithei-Sprache']],
        'mno' => [['Manobo languages', 'Manobo-Sprachen']],
        'moh' => [['Mohawk', 'Mohawk-Sprache']],
        'mon' => [['Mongolian', 'Mongolisch']],
        'mos' => [['Mossi', 'Mossi-Sprache']],
        'mul' => [['Multiple languages', 'Mehrere Sprachen']],
        'mun' => [['Munda languages', 'Mundasprachen (Andere)']],
        'mus' => [['Creek', 'Muskogisch']],
        'mwl' => [['Mirandese', 'Mirandesisch']],
        'mwr' => [['Marwari', 'Marwari']],
        'myn' => [['Mayan languages', 'Maya-Sprachen']],
        'myv' => [['Erzya', 'Erza-Mordwinisch']],
        'nah' => [['Nahuatl languages', 'Nahuatl']],
        'nai' => [['North American Indian languages', 'Indianersprachen, Nordamerika (Andere)']],
        'nap' => [['Neapolitan', 'Neapel / Mundart']],
        'nau' => [['Nauru', 'Nauruanisch']],
        'nav' => [['Navajo; Navaho', 'Navajo-Sprache']],
        'nbl' => [['Ndebele, South; South Ndebele', 'Ndebele-Sprache (Transvaal)']],
        'nde' => [['Ndebele, North; North Ndebele', 'Ndebele-Sprache (Simbabwe)']],
        'ndo' => [['Ndonga', 'Ndonga']],
        'nds' => [['Low German; Low Saxon; German, Low; Saxon, Low', 'Niederdeutsch']],
        'nep' => [['Nepali (macrolanguage)', 'Nepali']],
        'new' => [['Nepal Bhasa; Newari', 'Newari']],
        'nia' => [['Nias', 'Nias-Sprache']],
        'nic' => [['Niger-Kordofanian languages', 'Nigerkordofanische Sprachen (Andere)']],
        'niu' => [['Niuean', 'Niue-Sprache']],
        'nno' => [['Norwegian Nynorsk; Nynorsk, Norwegian', 'Nynorsk']],
        'nob' => [['Bokmål, Norwegian; Norwegian Bokmål', 'Bokmål']],
        'nog' => [['Nogai', 'Nogaisch']],
        'non' => [['Norse, Old', 'Altnorwegisch']],
        'nor' => [['Norwegian', 'Norwegisch']],
        'nqo' => [['N\'Ko', 'N\'Ko']],
        'nso' => [['Pedi; Sepedi; Northern Sotho', 'Pedi-Sprache']],
        'nub' => [['Nubian languages', 'Nubische Sprachen']],
        'nwc' => [['Classical Newari; Old Newari; Classical Nepal Bhasa', 'Alt-Newari']],
        'nya' => [['Chichewa; Chewa; Nyanja', 'Nyanja-Sprache']],
        'nym' => [['Nyamwezi', 'Nyamwezi-Sprache']],
        'nyn' => [['Nyankole', 'Nkole-Sprache']],
        'nyo' => [['Nyoro', 'Nyoro-Sprache']],
        'nzi' => [['Nzima', 'Nzima-Sprache']],
        'oci' => [['Occitan (post 1500)', 'Okzitanisch']],
        'oji' => [['Ojibwa', 'Ojibwa-Sprache']],
        'ori' => [['Oriya (macrolanguage)', 'Oriya-Sprache']],
        'orm' => [['Oromo', 'Galla-Sprache']],
        'osa' => [['Osage', 'Osage-Sprache']],
        'oss' => [['Ossetian; Ossetic', 'Ossetisch']],
        'ota' => [['Turkish, Ottoman (1500-1928)', 'Osmanisch']],
        'oto' => [['Otomian languages', 'Otomangue-Sprachen']],
        'paa' => [['Papuan languages', 'Papuasprachen (Andere)']],
        'pag' => [['Pangasinan', 'Pangasinan-Sprache']],
        'pal' => [['Pahlavi', 'Mittelpersisch']],
        'pam' => [['Pampanga; Kapampangan', 'Pampanggan-Sprache']],
        'pan' => [['Panjabi; Punjabi', 'Pandschabi-Sprache']],
        'pap' => [['Papiamento', 'Papiamento']],
        'pau' => [['Palauan', 'Palau-Sprache']],
        'peo' => [['Persian, Old (ca.600-400 B.C.)', 'Altpersisch']],
        'phi' => [['Philippine languages', 'Philippinisch-Austronesisch (Andere)']],
        'phn' => [['Phoenician', 'Phönikisch']],
        'pli' => [['Pali', 'Pali']],
        'pol' => [['Polish', 'Polnisch']],
        'pon' => [['Pohnpeian', 'Ponapeanisch']],
        'por' => [['Portuguese', 'Portugiesisch']],
        'pra' => [['Prakrit languages', 'Prakrit']],
        'pro' => [['Provençal, Old (to 1500);Occitan, Old (to 1500)', 'Altokzitanisch']],
        'pus' => [['Pushto; Pashto', 'Paschtu']],
        'qaa-qtz' => [['Reserved for local use', 'Reserviert für lokale Verwendung']],
        'que' => [['Quechua', 'Quechua-Sprache']],
        'raj' => [['Rajasthani', 'Rajasthani']],
        'rap' => [['Rapanui', 'Osterinsel-Sprache']],
        'rar' => [['Rarotongan; Cook Islands Maori', 'Rarotonganisch']],
        'roa' => [['Romance languages', 'Romanische Sprachen (Andere)']],
        'roh' => [['Romansh', 'Rätoromanisch']],
        'rom' => [['Romany', 'Romani (Sprache)']],
        'rum' => [['Romanian; Moldavian; Moldovan', 'Rumänisch'], [true, 'ron']],
        'ron' => [['Romanian; Moldavian; Moldovan', 'Rumänisch'], [false, 'rum']],
        'run' => [['Rundi', 'Rundi-Sprache']],
        'rup' => [['Aromanian; Arumanian; Macedo-Romanian', 'Aromunisch']],
        'rus' => [['Russian', 'Russisch']],
        'sad' => [['Sandawe', 'Sandawe-Sprache']],
        'sag' => [['Sango', 'Sango-Sprache']],
        'sah' => [['Yakut', 'Jakutisch']],
        'sai' => [['South American Indian languages', 'Indianersprachen, Südamerika (Andere)']],
        'sal' => [['Salishan languages', 'Salish-Sprache']],
        'sam' => [['Samaritan Aramaic', 'Samaritanisch']],
        'san' => [['Sanskrit', 'Sanskrit']],
        'sas' => [['Sasak', 'Sasak']],
        'sat' => [['Santali', 'Santali']],
        'scn' => [['Sicilian', 'Sizilianisch']],
        'sco' => [['Scots', 'Schottisch']],
        'sel' => [['Selkup', 'Selkupisch']],
        'sem' => [['Semitic languages', 'Semitische Sprachen (Andere)']],
        'sga' => [['Irish, Old (to 900)', 'Altirisch']],
        'sgn' => [['Sign Languages', 'Zeichensprachen']],
        'shn' => [['Shan', 'Schan-Sprache']],
        'sid' => [['Sidamo', 'Sidamo-Sprache']],
        'sin' => [['Sinhala; Sinhalese', 'Singhalesisch']],
        'sio' => [['Siouan languages', 'Sioux-Sprachen (Andere)']],
        'sit' => [['Sino-Tibetan languages', 'Sinotibetische Sprachen (Andere)']],
        'sla' => [['Slavic languages', 'Slawische Sprachen (Andere)']],
        'slo' => [['Slovak', 'Slowakisch'], [true, 'slk']],
        'slk' => [['Slovak', 'Slowakisch'], [false, 'slo']],
        'slv' => [['Slovenian', 'Slowenisch']],
        'sma' => [['Southern Sami', 'Südsaamisch']],
        'sme' => [['Northern Sami', 'Nordsaamisch']],
        'smi' => [['Sami languages', 'Saamisch']],
        'smj' => [['Lule Sami', 'Lulesaamisch']],
        'smn' => [['Inari Sami', 'Inarisaamisch']],
        'smo' => [['Samoan', 'Samoanisch']],
        'sms' => [['Skolt Sami', 'Skoltsaamisch']],
        'sna' => [['Shona', 'Schona-Sprache']],
        'snd' => [['Sindhi', 'Sindhi-Sprache']],
        'snk' => [['Soninke', 'Soninke-Sprache']],
        'sog' => [['Sogdian', 'Sogdisch']],
        'som' => [['Somali', 'Somali']],
        'son' => [['Songhai languages', 'Songhai-Sprache']],
        'sot' => [['Sotho, Southern', 'Süd-Sotho-Sprache']],
        'spa' => [['Spanish; Castilian', 'Spanisch']],
        'srd' => [['Sardinian', 'Sardisch']],
        'srn' => [['Sranan Tongo', 'Sranantongo']],
        'srp' => [['Serbian', 'Serbisch']],
        'srr' => [['Serer', 'Serer-Sprache']],
        'ssa' => [['Nilo-Saharan languages', 'Nilosaharanische Sprachen (Andere)']],
        'ssw' => [['Swati', 'Swasi-Sprache']],
        'suk' => [['Sukuma', 'Sukuma-Sprache']],
        'sun' => [['Sundanese', 'Sundanesisch']],
        'sus' => [['Susu', 'Susu']],
        'sux' => [['Sumerian', 'Sumerisch']],
        'swa' => [['Swahili (macrolanguage)', 'Swahili']],
        'swe' => [['Swedish', 'Schwedisch']],
        'syc' => [['Classical Syriac', 'Syrisch']],
        'syr' => [['Syriac', 'Neuostaramäisch']],
        'tah' => [['Tahitian', 'Tahitisch']],
        'tai' => [['Tai languages', 'Thaisprachen (Andere)']],
        'tam' => [['Tamil', 'Tamil']],
        'tat' => [['Tatar', 'Tatarisch']],
        'tel' => [['Telugu', 'Telugu-Sprache']],
        'tem' => [['Timne', 'Temne-Sprache']],
        'ter' => [['Tereno', 'Tereno-Sprache']],
        'tet' => [['Tetum', 'Tetum-Sprache']],
        'tgk' => [['Tajik', 'Tadschikisch']],
        'tgl' => [['Tagalog', 'Tagalog']],
        'tha' => [['Thai', 'Thailändisch']],
        'tig' => [['Tigre', 'Tigre-Sprache']],
        'tir' => [['Tigrinya', 'Tigrinja-Sprache']],
        'tiv' => [['Tiv', 'Tiv-Sprache']],
        'tkl' => [['Tokelau', 'Tokelauanisch']],
        'tlh' => [['Klingon; tlhIngan-Hol', 'Klingonisch']],
        'tli' => [['Tlingit', 'Tlingit-Sprache']],
        'tmh' => [['Tamashek', 'Tamašeq']],
        'tog' => [['Tonga (Nyasa)', 'Tonga (Bantusprache, Sambia)']],
        'ton' => [['Tonga (Tonga Islands)', 'Tongaisch']],
        'tpi' => [['Tok Pisin', 'Neumelanesisch']],
        'tsi' => [['Tsimshian', 'Tsimshian-Sprache']],
        'tsn' => [['Tswana', 'Tswana-Sprache']],
        'tso' => [['Tsonga', 'Tsonga-Sprache']],
        'tuk' => [['Turkmen', 'Turkmenisch']],
        'tum' => [['Tumbuka', 'Tumbuka-Sprache']],
        'tup' => [['Tupi languages', 'Tupi-Sprache']],
        'tur' => [['Turkish', 'Türkisch']],
        'tut' => [['Altaic languages', 'Altaische Sprachen (Andere)']],
        'tvl' => [['Tuvalu', 'Elliceanisch']],
        'twi' => [['Twi', 'Twi-Sprache']],
        'tyv' => [['Tuvinian', 'Tuwinisch']],
        'udm' => [['Udmurt', 'Udmurtisch']],
        'uga' => [['Ugaritic', 'Ugaritisch']],
        'uig' => [['Uighur; Uyghur', 'Uigurisch']],
        'ukr' => [['Ukrainian', 'Ukrainisch']],
        'umb' => [['Umbundu', 'Mbundu-Sprache']],
        'und' => [['Undetermined', 'Nicht zu entscheiden']],
        'urd' => [['Urdu', 'Urdu']],
        'uzb' => [['Uzbek', 'Usbekisch']],
        'vai' => [['Vai', 'Vai-Sprache']],
        'ven' => [['Venda', 'Venda-Sprache']],
        'vie' => [['Vietnamese', 'Vietnamesisch']],
        'vol' => [['Volapük', 'Volapük']],
        'vot' => [['Votic', 'Wotisch']],
        'wak' => [['Wakashan languages', 'Wakash-Sprachen']],
        'wal' => [['Wolaitta; Wolaytta', 'Walamo-Sprache']],
        'war' => [['Waray', 'Waray']],
        'was' => [['Washo', 'Washo-Sprache']],
        'wen' => [['Sorbian languages', 'Sorbisch (Andere)']],
        'wln' => [['Walloon', 'Wallonisch']],
        'wol' => [['Wolof', 'Wolof-Sprache']],
        'xal' => [['Kalmyk; Oirat', 'Kalmückisch']],
        'xho' => [['Xhosa', 'Xhosa-Sprache']],
        'yao' => [['Yao', 'Yao-Sprache (Bantusprache)']],
        'yap' => [['Yapese', 'Yapesisch']],
        'yid' => [['Yiddish', 'Jiddisch']],
        'yor' => [['Yoruba', 'Yoruba-Sprache']],
        'ypk' => [['Yupik languages', 'Ypik-Sprachen']],
        'zap' => [['Zapotec', 'Zapotekisch']],
        'zbl' => [['Blissymbols; Blissymbolics; Bliss', 'Bliss-Symbol']],
        'zen' => [['Zenaga', 'Zenaga']],
        'zgh' => [['Standard Moroccan Tamazight', '']],
        'zha' => [['Zhuang; Chuang', 'Zhuang']],
        'znd' => [['Zande languages', 'Zande-Sprachen']],
        'zul' => [['Zulu', 'Zulu-Sprache']],
        'zun' => [['Zuni', 'Zuñi-Sprache']],
        'zxx' => [['No linguistic content; Not applicable', 'Kein linguistischer Inhalt']],
        'zza' => [['Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki', 'Zazaki']]
    ];

    /**
     * Checks if iso code exist as ISO 639-2/B.
     *
     * This function tests whether a corresponding ISO 639-2 code exists in the constant array.
     * If an alternative version exists for that code, only true is returned for the bibliographic version.
     *
     * @param string $isoCode The iso code
     * @return bool True if iso code exist as
     */
    public static function iso6392BCodeExists(string $isoCode): bool
    {
        return array_key_exists($isoCode, self::ISO_639_2) && (count(self::ISO_639_2[$isoCode]) === 1
                || self::ISO_639_2[$isoCode][1][0]);
    }

}
